services:
  plant-watering-dev:
    image: plant-watering-dev
    build:
      context: .
      dockerfile: DevOps/Dockerfile
    container_name: plant-watering-dev
    volumes:
      # Mount the current directory to /workspace with read/write access
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true