wasm:
    cd /workspace/Simulation/ts && npx esbuild app.ts --bundle --outfile=../app.bundle.js --format=esm
    cd /workspace/Simulation/ && meson setup buildwasm --cross-file emscripten.ini --wipe
    meson compile -C buildwasm
    cd /workspace/Simulation/buildwasm && emrun --no_browser --port 8000 .
