sim:
    #!/usr/bin/env bash
    set -e
    . /opt/emsdk/emsdk_env.sh
    cd /workspace/Simulation/ts
    npx esbuild app.ts --bundle --outfile=/workspace/Simulation/app.bundle.js --format=esm
    cd /workspace/Simulation
    meson setup buildwasm --cross-file emscripten.ini --wipe
    meson compile -C buildwasm
    emrun --no_browser --port 8000 /workspace/Simulation/